# Generated by Django 2.0.1 on 2018-01-05 17:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_auto_20180104_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.PositiveSmallIntegerField(choices=[(0, 'Math'), (1, 'Programming')])),
                ('num_correct', models.IntegerField(default=uuid.uuid4)),
                ('num_incorrect', models.IntegerField(default=uuid.uuid4)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student')),
            ],
        ),
    ]
