# Generated by Django 2.0.1 on 2018-01-04 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_auto_20180104_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamePuzzle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.IntegerField()),
                ('least_steps', models.IntegerField(default=2147483647)),
                ('puzzle_string', models.CharField(max_length=5000000)),
            ],
        ),
        migrations.CreateModel(
            name='GameSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_steps', models.IntegerField()),
                ('correct', models.BooleanField(default=False)),
                ('solution_string', models.CharField(max_length=5000000)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student')),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programming.GamePuzzle')),
            ],
        ),
    ]
