# Generated by Django 2.0.1 on 2018-01-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booleananswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='integeranswer',
            name='student',
        ),
        migrations.DeleteModel(
            name='BooleanAnswer',
        ),
        migrations.DeleteModel(
            name='IntegerAnswer',
        ),
    ]
