# Generated by Django 2.0.1 on 2018-01-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180104_1905'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activequestion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='activequestion',
            name='student',
        ),
        migrations.DeleteModel(
            name='ActiveQuestion',
        ),
    ]
