# Generated by Django 2.0.1 on 2018-01-04 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mathstack', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_text', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathstack.Student')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='activequestion',
            unique_together={('student', 'q_text')},
        ),
    ]
