# Generated by Django 2.0.1 on 2018-01-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathstack', '0002_auto_20180104_1348'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activequestion',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='activequestion',
            name='student',
        ),
        migrations.RemoveField(
            model_name='booleananswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='integeranswer',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='ActiveQuestion',
        ),
        migrations.DeleteModel(
            name='BooleanAnswer',
        ),
        migrations.DeleteModel(
            name='IntegerAnswer',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
