# Generated by Django 2.0.1 on 2018-01-04 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_auto_20180104_1905'),
        ('mathstack', '0003_auto_20180104_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooleanAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_answer', models.BooleanField()),
                ('right_answer', models.BooleanField()),
                ('was_correct', models.BooleanField()),
                ('question', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student')),
            ],
        ),
        migrations.CreateModel(
            name='IntegerAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_answer', models.IntegerField()),
                ('right_answer', models.IntegerField()),
                ('was_correct', models.BooleanField()),
                ('question', models.CharField(max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Student')),
            ],
        ),
    ]
