# Generated by Django 2.0.1 on 2018-01-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathstack', '0005_auto_20180105_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booleanquestion',
            name='operator',
            field=models.CharField(choices=[('MODULUS', '%')], max_length=20),
        ),
    ]
